package com.example.headway_clone.demo.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.stereotype.Service;

/**
 * We are creating this EmailService to send OTP codes to users for password reset.
 * This service handles email composition and sending using QuickTales360@gmail.com.
 */
@Service
public class EmailService {

    @Autowired
    private JavaMailSender mailSender;

    @Value("${spring.mail.username}")
    private String fromEmail;

    /**
     * Send OTP code to user's email for password reset
     * This method is called when user requests password reset via forgot password
     * @param toEmail User's email address to send OTP
     * @param otpCode 4-digit OTP code generated by AuthService
     */
    public void sendOtpEmail(String toEmail, String otpCode) {
        try {
            SimpleMailMessage message = new SimpleMailMessage();
            message.setFrom(fromEmail); // QuickTales360@gmail.com
            message.setTo(toEmail);
            message.setSubject("QuickTales - Password Reset Code");

            String emailBody = String.format(
                    """
                            Hello,
                            
                            You requested to reset your password for your QuickTales account.
                            
                            Your verification code is: %s
                            
                            This code will expire in 5 minutes for security reasons.
                            
                            If you didn't request this password reset, please ignore this email.
                            Your account remains secure.
                            
                            Happy Reading!
                            The QuickTales Team
                            
                            ---
                            This is an automated message, please do not reply to this email.""",
                otpCode
            );

            message.setText(emailBody);
            mailSender.send(message);

        } catch (Exception e) {
            throw new RuntimeException("Failed to send OTP email: " + e.getMessage());
        }
    }

    /**
     * Send welcome email to newly registered users
     * @param toEmail User's email address
     * @param fullName User's full name
     */
    public void sendWelcomeEmail(String toEmail, String fullName) {
        try {
            SimpleMailMessage message = new SimpleMailMessage();
            message.setFrom(fromEmail);
            message.setTo(toEmail);
            message.setSubject("Welcome to QuickTales!");

            String emailBody = String.format(
                    """
                            Hi %s,
                            
                            Welcome to QuickTales! We're excited to have you join our community of book lovers.
                            
                            Start exploring our vast collection of book summaries and begin your reading journey today.
                            
                            Features you can enjoy:
                            • Quick book summaries for busy readers
                            • Track your reading progress and streaks
                            • Connect with friends and share recommendations
                            • Set reading goals and achieve milestones
                            
                            Happy Reading!
                            The QuickTales Team""",
                fullName
            );

            message.setText(emailBody);
            mailSender.send(message);

        } catch (Exception e) {
            // Don't throw exception for welcome email failure
            System.err.println("Failed to send welcome email: " + e.getMessage());
        }
    }

    /**
     * Send password reset confirmation email
     * @param toEmail User's email address
     * @param fullName User's full name
     */
    public void sendPasswordResetConfirmation(String toEmail, String fullName) {
        try {
            SimpleMailMessage message = new SimpleMailMessage();
            message.setFrom(fromEmail);
            message.setTo(toEmail);
            message.setSubject("QuickTales - Password Reset Successful");

            String emailBody = String.format(
                    """
                            Hi %s,
                            
                            Your password has been successfully reset.
                            
                            You can now log in to QuickTales with your new password.
                            
                            If you didn't make this change, please contact our support team immediately.
                            
                            Happy Reading!
                            The QuickTales Team""",
                fullName
            );

            message.setText(emailBody);
            mailSender.send(message);

        } catch (Exception e) {
            // Don't throw exception for confirmation email failure
            System.err.println("Failed to send confirmation email: " + e.getMessage());
        }
    }
}
